## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.7
  - 1.0
notifications:
  email: false

branches:
  only:
  - master
  - test

after_success:
    - julia -e 'using Pkg; Pkg.add("Coverage"); cd(Pkg.dir("StochasticPrograms")); using Coverage; Codecov.submit(process_folder())'